### ISSUE TITLE
feat: Firefoxのサポート

### ISSUE THREAD

**Issue by Robot-Inventor** [AranoYuki1/Misstter#5]
もし余裕があれば、Firefoxのサポートを追加していただきたいです。Firefoxをサポートすることになった場合、できる限りお手伝いさせていただきたいです。

**Comment by eniehack** [comment]
単純にFirefoxでも動作しそうなコードはMoziilaの提供する https://github.com/mozilla/webextension-polyfill を用いて、https://github.com/AranoYuki1/Misstter/blob/252dc041005c920450a825950dd822d4d745e2ae/src/content_script/content_script.tsx#L114 にあるような `chrome.*` を`browser.*`に置き換えることによって実現できます。

実際にwebextension-polyfillを用いて変更したものがここにあります: https://github.com/eniehack/Misstter/tree/support-firefox

しかし、試していただくとわかるのですが、Misskey APIへのアクセスは弾かれてしまいます。これは、Firefoxのセキュリティ機構がChromeのそれと比べ、[Content Security Policy（CSP）](https://developer.mozilla.org/ja/docs/Web/HTTP/CSP)（Webページが意図しないアクセスを行わないようにするためのセキュリティ機構？今回の場合は、拡張機能のスクリプト含めtwitter.com上で動作しているのスクリプトがmisskeyのサーバにアクセスすることがTwitter/X的には想定外の挙動であるため、その通信がブロックされてしまう）に対してしっかりと作られているためであると考えます。そのため、不特定多数のドメインに対してMisskey APIにアクセスできるように[`manifest.json`の`"content_security_policy"`](https://developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy)を定義する必要があるかと思います。

つまり、CSPの設定がうまく設定できればFirefoxへの対応は可能かと思います

**Comment by Robot-Inventor** [comment]
@eniehack 検証と情報共有ありがとうございます！

私も昨晩少し調べていたので途中経過を置いておきます。

まず、FirefoxはChromeのAPIとある程度互換性があるので、ポリフィルを入れなくても``chrome.*``のままで動きました。

一方で、ストレージにアクセスするには拡張機能IDを設定する必要があります。拡張機能IDは形式が指定されており、AMOで付与されるIDか、``英数字@英数字``の形式である必要があります。

```json
  "browser_specific_settings": {
    "gecko": {
      "id": "misstter@AranoYuki1"
    }
  }
```

次にCSPについてですが、``manifest.json``内の設定はおそらく拡張機能自身のCSPなので、ここを変えてもTwitterのCSPは上書きできないと思われます。

CSPを回避するには、私が調べた範囲ではHTTPヘッダーを書き換えるか、バックグラウンドスクリプトを使うという2つの方法があります。

前者はセキュリティーを弱める行為なので最終手段かと思います。後者は、FirefoxがManifest V3でbackground scriptを使うときに要求されるService Workerに対応していないという問題があります。

そのため、background scriptを使う場合は、Chrome向けとFirefox向けでmanifest.json（と一部のコード）を切り替える必要がありそうです。

**Comment by Robot-Inventor** [comment]
Manifest V2にしたところ、問題なく動作することを確認できました。ただ、Chrome向けとFirefox向けでどのようにManifestファイルを切り替えるかが課題です。

```json
{
  "manifest_version": 2,

  "name": "Misstter",
  "description": "Misstter",
  "version": "1.0",

  "browser_action": {
    "browser_style": true,
    "default_icon": "icon.png",
    "default_popup": "popup.html"
  },

  "content_scripts": [
      {
          "matches": ["https://twitter.com/*"],
          "js": ["js/vendor.js", "js/content_script.js"]
      }
  ],

  "permissions": [ "storage", "<all_urls>" ],

  "web_accessible_resources": [
      "misskey_icon.png",
      "pubilc_scope.svg"
  ],

  "browser_specific_settings": {
    "gecko": {
      "id": "misstter@AranoYuki1"
    }
  }
}
```

**Comment by Robot-Inventor** [comment]
[webextension-toolbox](https://github.com/webextension-toolbox/webextension-toolbox)を使うか、独自のスクリプトを書くかすればManifest.jsonを切り替えられそうです。

**Comment by AranoYuki1** [comment]
@eniehack @Robot-Inventor 

お二人のお話を参考にFirefoxのサポートを追加しました！

対応には、[こちら](https://github.com/eniehack/Misstter/tree/support-firefox
)で用いられていた [webextension-polyfill](https://github.com/mozilla/webextension-polyfill) を用いました。
また、CSPの問題は投稿処理をbackgroundスクリプトに移すことで解決しています。（Chrome版も同様の処理にしました）

**Comment by eniehack** [comment]
対応ありがとうございます！
v1.0.3で動作が確認できました！

@Robot-Inventor さんも調査ありがとうございます！

**Comment by Robot-Inventor** [comment]
@AranoYuki1 @eniehack 

お二人ともありがとうございます！！！感謝です
